Import of MLEHMANN/IO-AIO-3.17 from CPAN.
gitpan-cpan-distribution: IO-AIO
gitpan-cpan-version:      3.17
gitpan-cpan-path:         MLEHMANN/IO-AIO-3.17.tar.gz
gitpan-cpan-author:       MLEHMANN
gitpan-cpan-maturity:     released

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2937,6 +2937,63 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 
+{ echo "$as_me:$LINENO: checking for sync_file_range" >&5
+echo $ECHO_N "checking for sync_file_range... $ECHO_C" >&6; }
+if test "${ac_cv_sync_file_range+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+
+#include <fcntl.h>
+int main(void)
+{
+   int fd = 0;
+   off64_t offset = 1;
+   off64_t nbytes = 1;
+   unsigned int flags = SYNC_FILE_RANGE_WAIT_BEFORE|SYNC_FILE_RANGE_WRITE|SYNC_FILE_RANGE_WAIT_AFTER;
+   ssize_t res;
+   res = sync_file_range (fd, offset, nbytes, flags);
+   return 0;
+}
+
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_sync_file_range=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_sync_file_range=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_sync_file_range" >&5
+echo "${ECHO_T}$ac_cv_sync_file_range" >&6; }
+test $ac_cv_sync_file_range = yes &&
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SYNC_FILE_RANGE 1
+_ACEOF
+
+
 
 
 cat >confcache <<\_ACEOF
