Import of MLEHMANN/IO-AIO-3.01 from CPAN.
gitpan-cpan-distribution: IO-AIO
gitpan-cpan-version:      3.01
gitpan-cpan-path:         MLEHMANN/IO-AIO-3.01.tar.gz
gitpan-cpan-author:       MLEHMANN
gitpan-cpan-maturity:     released

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -576,6 +576,7 @@ PACKAGE_VERSION=
 PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
+ac_unique_file="libeio/eio.h"
 ac_subst_vars='SHELL
 PATH_SEPARATOR
 PACKAGE_NAME
@@ -1627,7 +1628,8 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
-ac_config_headers="$ac_config_headers config.h"
+
+ac_config_headers="$ac_config_headers libeio/config.h"
 
 
 ac_ext=c
@@ -2551,6 +2553,95 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+{ echo "$as_me:$LINENO: checking for library containing pthread_create" >&5
+echo $ECHO_N "checking for library containing pthread_create... $ECHO_C" >&6; }
+if test "${ac_cv_search_pthread_create+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_func_search_save_LIBS=$LIBS
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char pthread_create ();
+int
+main ()
+{
+return pthread_create ();
+  ;
+  return 0;
+}
+_ACEOF
+for ac_lib in '' pthread pthreads pthreadVC2; do
+  if test -z "$ac_lib"; then
+    ac_res="none required"
+  else
+    ac_res=-l$ac_lib
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+  fi
+  rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_search_pthread_create=$ac_res
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext
+  if test "${ac_cv_search_pthread_create+set}" = set; then
+  break
+fi
+done
+if test "${ac_cv_search_pthread_create+set}" = set; then
+  :
+else
+  ac_cv_search_pthread_create=no
+fi
+rm conftest.$ac_ext
+LIBS=$ac_func_search_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_search_pthread_create" >&5
+echo "${ECHO_T}$ac_cv_search_pthread_create" >&6; }
+ac_res=$ac_cv_search_pthread_create
+if test "$ac_res" != no; then
+  test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: pthread functions not found" >&5
+echo "$as_me: error: pthread functions not found" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+
+
 { echo "$as_me:$LINENO: checking for futimes" >&5
 echo $ECHO_N "checking for futimes... $ECHO_C" >&6; }
 if test "${ac_cv_futimes+set}" = set; then
@@ -2661,6 +2752,11 @@ echo "${ECHO_T}$ac_cv_readahead" >&6; }
 test $ac_cv_readahead = yes &&
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_READAHEAD 1
+_ACEOF
+
+test $ac_cv_readahead = yes &&
+cat >>confdefs.h <<\_ACEOF
+#define _GNU_SOURCE 1
 _ACEOF
 
 
@@ -2899,6 +2995,8 @@ test $ac_cv_sendfile = yes &&
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_SENDFILE 1
 _ACEOF
+
+
 
 
 cat >confcache <<\_ACEOF
@@ -3443,7 +3541,7 @@ cat >>$CONFIG_STATUS <<\_ACEOF
 for ac_config_target in $ac_config_targets
 do
   case $ac_config_target in
-    "config.h") CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
+    "libeio/config.h") CONFIG_HEADERS="$CONFIG_HEADERS libeio/config.h" ;;
 
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
